Repository salmorejo-hub-2/uvlhub, pull requests merged in 2024-12, with the labels that each got.

#36 Feat/ implemented CI workflow
  .github/workflows/ci2.yml
Labels: enhancement

#37 feat/ CI workflow changes
  .github/workflows/ci2.yml
Labels: enhancement

#38 Feat/WI2.6 Search Queries [Ref #6]
  app/modules/explore/templates/explore/indexSearch.html
  app/modules/exploreuvl/assets/scripts.js
  app/modules/exploreuvl/repositories.py
  app/modules/exploreuvl/routes.py
  app/modules/exploreuvl/services.py
  app/modules/exploreuvl/templates/exploreuvl/index.html
  app/modules/exploreuvl/tests/__init__.py
  app/modules/exploreuvl/tests/locustfile.py
  app/modules/exploreuvl/tests/test_selenium.py
  app/modules/exploreuvl/tests/test_unit.py
  app/modules/featuremodel/models.py
Labels: enhancement

#40 Feat/WI2.3 improve UI Ref #3
  app/static/css/app-dark.css
  app/static/css/app.css
  app/static/css/dropzone-dark.css
  app/static/css/own-dark.css
  app/static/css/own.css
Labels: enhancement

#42 Feat/wi1 visualize uvl
  app/modules/dataset/tests/test_selenium.py
  app/modules/dataset/tests/test_unit.py
  requirements.txt
Labels: enhancement

#46 fix: WI2.1 fix selenium test previsualize error [Closes #45]
  app/modules/dataset/tests/test_selenium.py
Labels: bug

#50 Feat/ WI2.3-Improve-UI
  .github/workflows/render.yml
  app/modules/auth/seeders.py
  app/modules/dataset/tests/test_selenium.py
  app/modules/pytest.ini
  app/static/__init__.py
  app/static/css/app-dark(progreso).css
  app/static/css/app-dark.css
  app/static/js/app.js
  app/static/js/tests/__init__.py
  app/static/js/tests/test_selenium.py
  app/static/js/tests/test_unit.py
  app/static/js/theme-toggle.js
  app/templates/400.html
  app/templates/401.html
  app/templates/404.html
  app/templates/500.html
  app/templates/base_template.html
  discordbot/pytest.ini
  discordbot/src/commands/dataset_commands.py
  discordbot/src/commands/token_commands.py
  discordbot/tests/test_dataset_commands.py
Labels: enhancement

#52 docs: Documentation [Closes #28]
  docs/salmorejo-hub-2/Diario de grupo.md
  docs/salmorejo-hub-2/Documento del proyecto.md
Labels: documentation

#54 feat/ Changed the label of the feature models explore [Closes #53]
  app/modules/exploreuvl/templates/exploreuvl/index.html
Labels: enhancement
